# Generated by Django 4.2.11 on 2024-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0009_remove_archive_preview_text_remove_archive_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='final_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
